---
title: "JSC370 Final Project"
author: "Evelyn Chou"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

## Project Description
Bike share systems are programs that offer short term bike rentals to inhabitants of a city, providing a convenient and cheaper alternative to purchasing a bike for thousands of dollars. Bike Share Toronto, Toronto's bike share system, offers both one time bike rentals, and annual memberships for a considerably cheaper alternative to purchasing a new bike. In a city such as Toronto, where bike thefts are rampant, they also offer the security of not having to worry about storing your bike in a secure location. Bike Share Toronto has over 600 stations across the city where you can rent and dock bikes. This program is utilized for a multitude of purposes including commute and leisure. 

Toronto's Open Data repository offers monthly data on Bike Share Toronto's ridership, including variables such as the start and end time of the rental, the bike dock the rental was from, and so much more. Of particular interest in this report is the start date of the rental, which will be used to count the total number of bike rentals in a given day. 

Toronto's Open Data repository also offers data on Bike Share Toronto's rental stations, including variables such as the station id, station coordinates (longitude and latitude), types of payments accepted at the station, and many more that will not be used in this report. 

Canada's government website stores data on the historical weather for all weather stations in Canada. Of particular interest in this report is the historical daily weather in Toronto's weather station. Weather variables in this dataset include maximum, minimum, and average daily temperature (°C), total daily precipitation (mm), and total daily snow (cm).

This study investigates if weather conditions and temporal factors influence the number of bike share users on a given day in Toronto. This investigation will be conducted first with the total daily bike rental count for all stations, and with the daily bike rental count for each starting station. By understanding the relationship between weather factors, temporal factors, and bike share ridership, the city can understand when maintenance should be performed to avoid inconveniencing members, and when promotions would be viable. 

To do this, I will collect Toronto's Open data repository data on Bike Share Toronto, and Canada's government on historical daily weather in Toronto's weather station from January 2020 to December 2022.


## Access the Project
To view a complete pdf of the report, [click here](https://github.com/evelyn323/JSC370-Final-Project/raw/main/Report/Report.pdf).

Note that many of the visualizations are interactive, which is not rendered in the pdf report. Please refer to the relevant visualization in the website for the interactive version. All content in the pdf report is also contained on the webpage.







